-- =============================================================================
-- Color of Nature — Seed Data
-- =============================================================================
-- Product data is sourced from Odoo ERP via the sync-products edge function.
-- No seed data is needed — run `sync-products` to populate the database.
-- This file is intentionally empty.
